version: '3'
services:
  jekyll:
    image: "jekyll/jekyll:${JEKYLL_VERSION}"
    environment:
      - "JEKYLL_GITHUB_TOKEN:${JEKYLL_GITHUB_TOKEN}"
      # - "FORCE_POLLING:true"
    ports:
      - "4000:4000"
      - "35729:35729" # Live reload port
    volumes:
      - ./src:/srv/jekyll
    # stdin_open: true
    # tty: true
    command: jekyll serve --force_polling -H 0.0.0.0 -P 4000 --livereload
    # command: bundle exec jekyll s --force_polling -H 0.0.0.0 -P 4000 --livereload
  # dev:
  #   image: alpine:latest
  #   entrypoint: "/bin/sh"
  #   stdin_open: true
  #   tty: true